//PROGRAM THAT STORES THE PRICE OF THREE PRODUCTS
//creating variables for the three products
var BREAD =55000;
var JUICE = 30000;
var CAKE = 100000;
//getting the Total of the three products
TOTAL = CAKE+JUICE+BREAD;
//output for the Total of the three products
console.log("The total of the products is",TOTAL)
//statement condition to determin whether customer gets discount if Total exceeds 100000
if(TOTAL>=100000){
    console.log("DICOUNT GIVEN")
}


    
