//SWITCH STATEMENT
//OPTION FOR USER TO OPT FOR A PREFERD NETWORK

console.log("choose prefered network")
console.log("MTN")
console.log("AIRTEL")
console.log("AFRICELL")
console.log()


let prefered_NETWORK= "AFRICELL"
switch(prefered_NETWORK){
    case 1:
        console.log("MTN:1");
    break;
    case 2:
        console.log("AIRTEL:2");
    break;
    default:
        console.log("AFRICELL:3")  

}